-- 1. List each customer's name and the total amount they've spent on orders.
SELECT 
    c.name AS customer_name,
    SUM(o.total_amount) AS total_spent
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.name;


-- 2. List the name and registration date of customers who placed orders in April 2024.
SELECT DISTINCT 
    c.name,
    c.registration_date
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
WHERE o.order_date BETWEEN '2024-04-01' AND '2024-04-30';

-- OR

SELECT
    c.name,
    c.registration_date,
    o.order_date
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
WHERE TO_CHAR(o.order_date, 'MM-YYYY') = '04-2024';


-- 3. Calculate the average order value (total_amount) for each customer, showing their name and average.
SELECT 
    c.name AS customer_name,
    ROUND(AVG(o.total_amount), 2) AS average_order_value
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.name;


-- 4. For each order, show the order ID and the percentage it represents of the customer's total spending.
SELECT
    o.order_id,
    ROUND((o.total_amount / total_by_customer.total) * 100, 2) AS percentage_of_total
FROM orders o
JOIN (
  SELECT customer_id, SUM(total_amount) AS total
  FROM orders
  GROUP BY customer_id
) total_by_customer ON o.customer_id = total_by_customer.customer_id;


-- 5. Display each customer's name and the total quantity of products they purchased.
SELECT 
    c.name AS customer_name,
    SUM(oi.quantity) AS total_items_purchased
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.name ASC;


-- 6. List each product and the total value generated by it (quantity * unit_price), ordered from largest to smallest.
SELECT
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS total_value
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_value DESC;


-- 7. List the 3 best-selling products in total quantity.
SELECT
  product_name,
  quantity
FROM order_items 
ORDER BY quantity DESC
LIMIT 3;


-- 8. Display the name of customers whose average ticket exceeds R$200.
SELECT 
    c.name, 
    ROUND(AVG(o.total_amount), 2) AS avg_ticket
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
GROUP BY c.name
HAVING AVG(o.total_amount) > 200;


-- 9. For each order, calculate the total amount of the items (SUM(quantity * unit_price)) and compare 
-- it with the total_amount field in the orders table. Display the difference between the two.
SELECT 
    o.order_id, 
    o.total_amount,
    SUM(oi.quantity * oi.unit_price) AS calculated_total,
    ROUND(SUM(oi.quantity * oi.unit_price) - o.total_amount, 2) AS difference
FROM orders o
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY o.order_id, o.total_amount;


-- 10. Find the average order amount per customer only among those who have ordered at least 3 different products.
SELECT 
    c.name,
    ROUND(AVG(o.total_amount), 2) AS avg_amount,
    COUNT(DISTINCT oi.product_name)
FROM orders o
INNER JOIN customers c ON o.customer_id = c.customer_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY c.name
HAVING COUNT(DISTINCT oi.product_name) >= 3;

